### ISSUE TITLE
Trong file convert bị chèn time vào trường năm đầu tư

### ISSUE THREAD

**Issue by congto** [hocchudong/netbox-import-tool#16]
Loại bỏ thời gian trong file đầu ra

![image](https://github.com/user-attachments/assets/dfe49677-4935-49f7-9d4b-58b2a67cba99)

![image](https://github.com/user-attachments/assets/01fa5f25-4367-42fb-89f7-d4a4210ca671)

**Comment by Ducmanh28** [comment]
đã hoàn thành fix
