### ISSUE TITLE
Kiểm tra lại file requirement.txt trong tool auto import device 

### ISSUE THREAD

**Issue by congto** [hocchudong/netbox-import-tool#28]
File  đang có lỗi như sau

- Không chỉ ra phiên bản của các gói

- Dòng chứa gói `re` (dòng 6) đang có nhầm lẫn, thực tế không có gói đó.
![image](https://github.com/user-attachments/assets/66ec69d8-24a1-46b4-86ea-2f6042133578)

**Comment by Ducmanh28** [comment]
- gói 're' là một gói chuẩn nên sẽ không cần cài nữa ==> Đã fix
- Vì thêm các phiên bản cụ thể cho các gói sẽ dẫn đến việc cài đặt bị lỗi trên các hệ điều hành khác nhau. Ví dụ Linux sẽ cài đặt các gói phiên bản khác so với Windows. Vậy nên chỉ cần pip install các gói mặc định thì tool đều sẽ chạy được
