### ISSUE TITLE
Không thấy có các giá trị của custom field được add trong thiết bị

### ISSUE THREAD

**Issue by congto** [hocchudong/netbox-import-tool#29]
Khi chạy tool auto import device, không thấy các cột custom field được import vào trong thiết bị, như device owner, Year of Investment, Contract Number

![image](https://github.com/user-attachments/assets/dd2a13cc-a3b4-4341-8da4-f0a57d322f79)

**Comment by Ducmanh28** [comment]
đã fix trong toàn bộ các phiên bản
